#
# $Id: Makefile,v 1.1.4.1 2006-02-02 07:00:25 knicewar Exp $
#
# Copyright Keith Nicewarner.  All rights reserved.
#
# Install the configuration header files.
#

INSTALL_HEADER_DIR = system
INSTALL_HEADERS    = units_config.h

UNITS_ROOT = ..
include ../make_rules/common.rules
