
CXX = /usr/bin/g++ -std=c++14

all: \
  units \
  units2 \
  units3 \
  units4 \
  units5 \
  decibel \
  bel


units: units.cpp
	$(CXX) -g -o units units.cpp

units2: units2.cpp
	$(CXX) -g -o units2 units2.cpp

units3: units3.cpp
	$(CXX) -g -o units3 units3.cpp

units4: units4.cpp
	$(CXX) -g -o units4 units4.cpp

units5: units5.cpp
	$(CXX) -g -o units5 units5.cpp

decibel: decibel.cpp
	$(CXX) -g -o decibel decibel.cpp

bel: bel.cpp
	$(CXX) -g -o bel bel.cpp

